/**
 * Creation repository — backend-neutral business logic for creations.
 *
 * Goes through `backend.data` (DataStore port). No Firebase imports.
 *
 * Wraps the same external API as the legacy `lib/firebase/creationService.ts`
 * so callers don't change. The legacy file is now a re-export shim.
 */

import { backend } from '@/lib/backend';
import { AppException } from '@/lib/api-utils';
import type { Creation, CreationType } from '@/types/creation.types';

const CREATIONS = 'creations';
const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 50;

// ── Public types (mirror legacy service for source-compat) ──────────

export interface SaveCreationInput {
  type: CreationType;
  title: string;
  prompt: string;
  content: Record<string, unknown>;
  media?: Array<{ url: string; type: string; alt: string }>;
  thumbnail?: string;
  aiMetadata: Record<string, unknown>;
  aiConceptsTaught: string[];
  curriculumTags?: string[];
  isPublic?: boolean;
  sessionId: string;
  remixedFromId?: string;
}

export interface ListCreationsFilters {
  type?: CreationType;
  isPublic?: boolean;
  limit?: number;
  cursor?: string;
}

export interface PublicListFilters {
  type?: CreationType;
  sort: 'trending' | 'newest';
  limit?: number;
  cursor?: string;
}

export interface ListCreationsResult {
  items: Creation[];
  nextCursor: string | null;
  hasMore: boolean;
}

// ── Operations ──────────────────────────────────────────────────────

/**
 * Save a new creation. Returns id + share URL.
 *
 * The new id is generated by the backend (via `backend.data.create` with
 * id=null). We then update the doc with `shareUrl: /view/<id>` so it carries
 * its own URL. Two writes is fine for this hot path — the second is a small
 * partial update.
 */
export async function saveCreation(
  input: SaveCreationInput,
): Promise<{ id: string; shareUrl: string }> {
  const status = (input.isPublic ?? false) ? 'published' : 'draft';
  const id = await backend.data.create<Partial<Creation>>(CREATIONS, null, {
    type: input.type,
    title: input.title,
    status,
    prompt: input.prompt,
    content: input.content as never,
    media: input.media ?? [],
    thumbnail: input.thumbnail,
    aiMetadata: input.aiMetadata as never,
    sessionId: input.sessionId,
    viewCount: 0,
    shareCount: 0,
    downloadCount: 0,
    likeCount: 0,
    aiConceptsTaught: input.aiConceptsTaught,
    curriculumTags: input.curriculumTags ?? [],
    remixedFromId: input.remixedFromId,
    remixCount: 0,
    isPublic: input.isPublic ?? false,
  });

  const shareUrl = `/view/${id}`;
  // Persist the shareUrl so it can be queried/displayed without recomputation.
  await backend.data.update<Creation>(CREATIONS, id, { shareUrl });

  // Fire-and-forget: bump remix counter on the original.
  if (input.remixedFromId) {
    incrementRemixCount(input.remixedFromId).catch(() => {
      // Non-critical — don't fail the save if the original is missing.
    });
  }

  return { id, shareUrl };
}

export async function getCreation(id: string): Promise<Creation> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  return doc;
}

export async function incrementView(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'viewCount', 1);
}

export async function incrementDownload(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'downloadCount', 1);
}

export async function incrementShare(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'shareCount', 1);
}

export async function incrementRemixCount(id: string): Promise<void> {
  await backend.data.increment(CREATIONS, id, 'remixCount', 1);
}

export async function archiveCreation(
  id: string,
  sessionId: string,
): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  if (doc.sessionId !== sessionId) {
    throw new AppException('FORBIDDEN', 'You do not own this creation', 403);
  }
  await backend.data.update<Creation>(CREATIONS, id, { status: 'archived' });
}

/**
 * List creations for a session, filtering archived in memory across multiple
 * batched queries (avoids needing a composite index on status).
 *
 * The legacy service used Firestore document IDs as cursors. The new
 * DataStore uses opaque base64 cursors. Since this is pre-launch, no live
 * cursors need to migrate.
 */
export async function listCreations(
  sessionId: string,
  filters: ListCreationsFilters = {},
): Promise<ListCreationsResult> {
  const limit = Math.min(filters.limit ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
  const batchSize = Math.max(limit * 2, 20);
  const maxBatches = 5;

  const where: Array<{ field: string; op: 'eq'; value: unknown }> = [
    { field: 'sessionId', op: 'eq', value: sessionId },
  ];
  if (filters.type) where.push({ field: 'type', op: 'eq', value: filters.type });

  const collected: Creation[] = [];
  let cursor: string | undefined = filters.cursor;

  for (let i = 0; i < maxBatches; i++) {
    const page = await backend.data.query<Creation>(CREATIONS, {
      where,
      orderBy: [{ field: 'createdAt', direction: 'desc' }],
      limit: batchSize,
      cursor,
    });

    const active = page.items.filter((c) => c.status !== 'archived');
    collected.push(...active);

    if (collected.length > limit || !page.hasMore) break;
    cursor = page.nextCursor ?? undefined;
  }

  const hasMore = collected.length > limit;
  const items = collected.slice(0, limit);
  const nextCursor =
    hasMore && items.length > 0
      ? // Re-encode cursor based on the last item's createdAt
        encodeIdCursor(items[items.length - 1]!.createdAt)
      : null;

  return { items, nextCursor, hasMore };
}

export async function listPublicCreations(
  filters: PublicListFilters,
): Promise<ListCreationsResult> {
  const limit = Math.min(filters.limit ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
  const sortField = filters.sort === 'trending' ? 'likeCount' : 'createdAt';
  const batchSize = Math.max(limit * 2, 20);
  const maxBatches = 5;

  const where: Array<{ field: string; op: 'eq'; value: unknown }> = [
    { field: 'isPublic', op: 'eq', value: true },
  ];
  if (filters.type) where.push({ field: 'type', op: 'eq', value: filters.type });

  const collected: Creation[] = [];
  let cursor: string | undefined = filters.cursor;

  for (let i = 0; i < maxBatches; i++) {
    const page = await backend.data.query<Creation>(CREATIONS, {
      where,
      orderBy: [{ field: sortField, direction: 'desc' }],
      limit: batchSize,
      cursor,
    });

    const active = page.items.filter((c) => c.status !== 'archived');
    collected.push(...active);

    if (collected.length > limit || !page.hasMore) break;
    cursor = page.nextCursor ?? undefined;
  }

  const hasMore = collected.length > limit;
  const items = collected.slice(0, limit);
  const nextCursor =
    hasMore && items.length > 0
      ? encodeIdCursor(
          (items[items.length - 1]! as unknown as Record<string, unknown>)[
            sortField
          ] as Date | string,
        )
      : null;

  return { items, nextCursor, hasMore };
}

/**
 * Top creators by recent public published creation count.
 * Reads up to 200 recent public creations and aggregates client-side.
 */
export async function getTopCreators(
  topN: number = 5,
): Promise<Array<{ sessionId: string; creationCount: number }>> {
  const page = await backend.data.query<Creation>(CREATIONS, {
    where: [{ field: 'isPublic', op: 'eq', value: true }],
    orderBy: [{ field: 'createdAt', direction: 'desc' }],
    limit: 200,
  });

  const counts = new Map<string, number>();
  for (const c of page.items) {
    if (c.status === 'archived') continue;
    counts.set(c.sessionId, (counts.get(c.sessionId) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, topN)
    .map(([sessionId, creationCount]) => ({ sessionId, creationCount }));
}

// ── Helpers ────────────────────────────────────────────────────────

function encodeIdCursor(value: Date | string): string {
  const v = value instanceof Date ? value.toISOString() : value;
  return Buffer.from(JSON.stringify({ v: [v] }), 'utf-8').toString('base64');
}
