/**
 * Creation repository — backend-neutral business logic for creations.
 *
 * Goes through `backend.data` (DataStore port). No Firebase imports.
 *
 * Wraps the same external API as the legacy `lib/firebase/creationService.ts`
 * so callers don't change. The legacy file is now a re-export shim.
 */

import { backend } from '@/lib/backend';
import { AppException } from '@/lib/api-utils';
import type { Creation, CreationType } from '@/types/creation.types';

const CREATIONS = 'creations';
const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 50;

// ── Public types (mirror legacy service for source-compat) ──────────

export interface SaveCreationInput {
  type: CreationType;
  title: string;
  prompt: string;
  content: Record<string, unknown>;
  media?: Array<{ url: string; type: string; alt: string }>;
  thumbnail?: string;
  aiMetadata: Record<string, unknown>;
  aiConceptsTaught: string[];
  curriculumTags?: string[];
  isPublic?: boolean;
  sessionId: string;
  remixedFromId?: string;
}

export interface ListCreationsFilters {
  type?: CreationType;
  isPublic?: boolean;
  limit?: number;
  cursor?: string;
}

export interface PublicListFilters {
  type?: CreationType;
  sort: 'trending' | 'newest';
  limit?: number;
  cursor?: string;
}

export interface ListCreationsResult {
  items: Creation[];
  nextCursor: string | null;
  hasMore: boolean;
}

// ── Operations ──────────────────────────────────────────────────────

/**
 * Save a new creation. Returns id + share URL.
 *
 * The new id is generated by the backend (via `backend.data.create` with
 * id=null). We then update the doc with `shareUrl: /view/<id>` so it carries
 * its own URL. Two writes is fine for this hot path — the second is a small
 * partial update.
 */
export async function saveCreation(
  input: SaveCreationInput,
): Promise<{ id: string; shareUrl: string }> {
  const status = (input.isPublic ?? false) ? 'published' : 'draft';
  const id = await backend.data.create<Partial<Creation>>(CREATIONS, null, {
    type: input.type,
    title: input.title,
    status,
    prompt: input.prompt,
    content: input.content as never,
    media: input.media ?? [],
    thumbnail: input.thumbnail,
    aiMetadata: input.aiMetadata as never,
    sessionId: input.sessionId,
    viewCount: 0,
    shareCount: 0,
    downloadCount: 0,
    likeCount: 0,
    aiConceptsTaught: input.aiConceptsTaught,
    curriculumTags: input.curriculumTags ?? [],
    remixedFromId: input.remixedFromId,
    remixCount: 0,
    isPublic: input.isPublic ?? false,
  });

  const shareUrl = `/view/${id}`;
  // Persist the shareUrl so it can be queried/displayed without recomputation.
  await backend.data.update<Creation>(CREATIONS, id, { shareUrl });

  // Fire-and-forget: bump remix counter on the original.
  if (input.remixedFromId) {
    incrementRemixCount(input.remixedFromId).catch(() => {
      // Non-critical — don't fail the save if the original is missing.
    });
  }

  return { id, shareUrl };
}

export async function getCreation(id: string): Promise<Creation> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  return doc;
}

export async function incrementView(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'viewCount', 1);
}

export async function incrementDownload(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'downloadCount', 1);
}

export async function incrementShare(id: string): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  await backend.data.increment(CREATIONS, id, 'shareCount', 1);
}

export async function incrementRemixCount(id: string): Promise<void> {
  await backend.data.increment(CREATIONS, id, 'remixCount', 1);
}

export async function archiveCreation(
  id: string,
  sessionId: string,
): Promise<void> {
  const doc = await backend.data.get<Creation>(CREATIONS, id);
  if (!doc) throw new AppException('NOT_FOUND', 'Creation not found', 404);
  if (doc.sessionId !== sessionId) {
    throw new AppException('FORBIDDEN', 'You do not own this creation', 403);
  }
  await backend.data.update<Creation>(CREATIONS, id, { status: 'archived' });
}

/**
 * List creations for a session.
 *
 * Filters archived in the query (composite index covers it) so a single
 * Firestore round-trip returns exactly `limit + 1` rows — no in-memory
 * scan-and-discard, no batched re-fetching. The previous batched-loop
 * implementation could read 200 docs per page worst-case at scale.
 */
export async function listCreations(
  sessionId: string,
  filters: ListCreationsFilters = {},
): Promise<ListCreationsResult> {
  const limit = Math.min(filters.limit ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);

  const where: Array<{ field: string; op: 'eq' | 'ne'; value: unknown }> = [
    { field: 'sessionId', op: 'eq', value: sessionId },
    { field: 'status', op: 'ne', value: 'archived' },
  ];
  if (filters.type) where.push({ field: 'type', op: 'eq', value: filters.type });

  const page = await backend.data.query<Creation>(CREATIONS, {
    where,
    orderBy: [{ field: 'createdAt', direction: 'desc' }],
    limit,
    cursor: filters.cursor,
  });

  return {
    items: page.items,
    nextCursor: page.nextCursor,
    hasMore: page.hasMore,
  };
}

export async function listPublicCreations(
  filters: PublicListFilters,
): Promise<ListCreationsResult> {
  const limit = Math.min(filters.limit ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
  const isTrending = filters.sort === 'trending';
  // Trending: primary sort by likeCount desc; tie-break by createdAt desc.
  // Composite index in firestore.indexes.json covers the full filter+sort
  // combination so we get `limit + 1` reads per page (no in-memory filter).
  const orderBy: Array<{ field: string; direction: 'desc' }> = isTrending
    ? [
        { field: 'likeCount', direction: 'desc' },
        { field: 'createdAt', direction: 'desc' },
      ]
    : [{ field: 'createdAt', direction: 'desc' }];

  const where: Array<{ field: string; op: 'eq' | 'ne'; value: unknown }> = [
    { field: 'isPublic', op: 'eq', value: true },
    { field: 'status', op: 'ne', value: 'archived' },
  ];
  if (filters.type) where.push({ field: 'type', op: 'eq', value: filters.type });

  const page = await backend.data.query<Creation>(CREATIONS, {
    where,
    orderBy,
    limit,
    cursor: filters.cursor,
  });

  return {
    items: page.items,
    nextCursor: page.nextCursor,
    hasMore: page.hasMore,
  };
}

/**
 * Top creators by recent public published creation count.
 *
 * Reads from the `leaderboards/topCreators` cache populated hourly by the
 * `leaderboard-refresh` scheduled function. Falls back to a live scan if
 * the cache is missing (first deploy, or cache wiped). Live scan reads
 * up to 200 recent creations — keep the fallback path bounded.
 */
export async function getTopCreators(
  topN: number = 5,
): Promise<Array<{ sessionId: string; creationCount: number }>> {
  const cached = await backend.data
    .get<{ entries: Array<{ sessionId: string; creationCount: number }> }>(
      'leaderboards',
      'topCreators',
    )
    .catch(() => null);

  if (cached?.entries?.length) {
    return cached.entries.slice(0, topN);
  }

  // Cache miss — live scan. The hourly cron will populate the cache shortly.
  const page = await backend.data.query<Creation>(CREATIONS, {
    where: [
      { field: 'isPublic', op: 'eq', value: true },
      { field: 'status', op: 'ne', value: 'archived' },
    ],
    orderBy: [{ field: 'createdAt', direction: 'desc' }],
    limit: 200,
  });

  const counts = new Map<string, number>();
  for (const c of page.items) {
    counts.set(c.sessionId, (counts.get(c.sessionId) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, topN)
    .map(([sessionId, creationCount]) => ({ sessionId, creationCount }));
}

