/**
 * Phase 4 (REPORT-001): parent-facing progress report PDF.
 *
 * Per-kid summary that pulls from data we already collect:
 * concepts mastered, creations by type, recent teacher feedback,
 * badges, streaks. Branded via the school-branding pipeline so the
 * letterhead + colours flow through automatically.
 */

import { jsPDF } from 'jspdf';
import { adminDb } from '@gsi/firebase/admin';
import { getKid } from '@gsi/firebase/kidService';
import { AppException } from '@/lib/api-utils';
import {
  getSchoolBranding,
  renderBrandedHeader,
  type ResolvedBranding,
} from './schoolBranding';
import type { Locale } from '@/lib/i18n/locales';

export type Range = 'month' | 'term' | 'year';

const STRINGS = {
  en: {
    title: (range: Range) =>
      `Progress report — ${range === 'month' ? 'past month' : range === 'term' ? 'this term' : 'this year'}`,
    student: 'Student',
    grade: 'Grade',
    school: 'School',
    summary: 'Summary',
    creations: 'Creations',
    creationsByType: 'Creations by type',
    conceptsMastered: 'AI concepts engaged',
    badges: 'Badges',
    streak: (cur: number, longest: number) =>
      `Current streak: ${cur} days · Longest: ${longest} days`,
    teacherFeedback: 'Recent teacher feedback',
    nextSteps: 'Suggested next steps',
    suggestion: (score: number) =>
      score < 5
        ? 'Try one new creation type this week — variety boosts long-term curiosity.'
        : 'Pick a single concept and try a follow-up creation that pushes it deeper.',
    footer: 'Generated by GSI AI Studio. Reach out to the teacher for any clarification.',
  },
  hi: {
    title: (range: Range) =>
      `प्रगति रिपोर्ट — ${range === 'month' ? 'पिछले माह' : range === 'term' ? 'इस सत्र' : 'इस वर्ष'}`,
    student: 'विद्यार्थी',
    grade: 'कक्षा',
    school: 'विद्यालय',
    summary: 'सारांश',
    creations: 'कुल रचनाएँ',
    creationsByType: 'प्रकार के अनुसार रचनाएँ',
    conceptsMastered: 'AI अवधारणाएँ',
    badges: 'बैज',
    streak: (cur: number, longest: number) =>
      `वर्तमान निरंतरता: ${cur} दिन · सबसे लंबी: ${longest} दिन`,
    teacherFeedback: 'हाल की शिक्षक टिप्पणियाँ',
    nextSteps: 'अगले कदम',
    suggestion: (score: number) =>
      score < 5
        ? 'इस सप्ताह एक नई रचना शैली आज़माएँ — विविधता जिज्ञासा बढ़ाती है।'
        : 'एक अवधारणा चुनें और उसे और गहराई से दर्शाने वाली रचना बनाएँ।',
    footer: 'GSI AI Studio द्वारा निर्मित। किसी भी प्रश्न के लिए शिक्षक से संपर्क करें।',
  },
};

function rangeStart(range: Range): Date {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  if (range === 'month') d.setMonth(d.getMonth() - 1);
  else if (range === 'term') d.setMonth(d.getMonth() - 4);
  else d.setFullYear(d.getFullYear() - 1);
  return d;
}

interface FeedbackRow {
  feedback: string;
  reviewedAt: Date;
  status: string;
}

async function loadRecentFeedback(
  kidId: string,
  fromDate: Date,
  limit = 5,
): Promise<FeedbackRow[]> {
  const snap = await adminDb
    .collection('submissions')
    .where('kidId', '==', kidId)
    .get();
  const rows: FeedbackRow[] = [];
  for (const doc of snap.docs) {
    const data = doc.data() as Record<string, unknown>;
    const reviewedAt =
      (data.reviewedAt as { toDate?: () => Date } | undefined)?.toDate?.();
    if (!reviewedAt || reviewedAt < fromDate) continue;
    const feedback = data.feedback as string | undefined;
    if (!feedback) continue;
    rows.push({
      feedback,
      reviewedAt,
      status: (data.status as string) ?? 'reviewed',
    });
  }
  return rows
    .sort((a, b) => b.reviewedAt.getTime() - a.reviewedAt.getTime())
    .slice(0, limit);
}

export interface RenderProgressReportInput {
  kidId: string;
  range?: Range;
  locale?: Locale;
}

export async function renderProgressReport(
  input: RenderProgressReportInput,
): Promise<{ pdf: Buffer; kidName: string }> {
  const range: Range = input.range ?? 'term';
  const locale: Locale = input.locale === 'hi' ? 'hi' : 'en';
  const t = STRINGS[locale];

  const kid = await getKid(input.kidId);
  if (!kid) {
    throw new AppException('NOT_FOUND', 'Student not found.', 404);
  }
  const branding: ResolvedBranding = kid.schoolId
    ? await getSchoolBranding(kid.schoolId)
    : {
        schoolName: 'GSI AI Studio',
        primaryColor: '#4F46E5',
        secondaryColor: '#EC4899',
      };

  const fromDate = rangeStart(range);
  const feedback = await loadRecentFeedback(input.kidId, fromDate);

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  renderBrandedHeader(doc, branding);

  const margin = 14;
  const pageW = doc.internal.pageSize.getWidth();
  const textW = pageW - margin * 2;
  let y = 36;

  doc.setFontSize(14);
  doc.setTextColor('#0f172a');
  doc.text(t.title(range), margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor('#475569');
  doc.text(`${t.student}: ${kid.name}`, margin, y);
  y += 5;
  if (kid.grade) {
    doc.text(`${t.grade}: ${kid.grade}`, margin, y);
    y += 5;
  }
  doc.text(`${t.school}: ${branding.schoolName}`, margin, y);
  y += 8;

  // Summary section
  doc.setFontSize(12);
  doc.setTextColor(branding.primaryColor);
  doc.text(t.summary, margin, y);
  y += 6;
  doc.setFontSize(11);
  doc.setTextColor('#0f172a');
  doc.text(`${t.creations}: ${kid.totalCreations ?? 0}`, margin, y);
  y += 5;
  if (kid.streak) {
    doc.setFontSize(10);
    doc.setTextColor('#475569');
    doc.text(t.streak(kid.streak.current ?? 0, kid.streak.longest ?? 0), margin, y);
    y += 5;
  }
  doc.text(`AI points: ${kid.aiPoints ?? 0}`, margin, y);
  y += 8;

  // Creations by type
  if (kid.creationsByType && Object.keys(kid.creationsByType).length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor);
    doc.text(t.creationsByType, margin, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor('#0f172a');
    for (const [type, count] of Object.entries(kid.creationsByType)) {
      doc.text(`• ${type}: ${count}`, margin + 4, y);
      y += 4.5;
    }
    y += 4;
  }

  // Concepts
  if (kid.conceptsLearned && kid.conceptsLearned.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor);
    doc.text(t.conceptsMastered, margin, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor('#0f172a');
    const wrapped = doc.splitTextToSize(
      kid.conceptsLearned.slice(0, 24).join(', '),
      textW,
    );
    doc.text(wrapped, margin, y);
    y += wrapped.length * 4 + 4;
  }

  // Badges
  if (kid.badges && kid.badges.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor);
    doc.text(t.badges, margin, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor('#0f172a');
    const wrapped = doc.splitTextToSize(
      kid.badges.slice(0, 16).join(', '),
      textW,
    );
    doc.text(wrapped, margin, y);
    y += wrapped.length * 4 + 4;
  }

  // Feedback
  if (feedback.length > 0) {
    if (y > 220) {
      doc.addPage();
      renderBrandedHeader(doc, branding);
      y = 40;
    }
    doc.setFontSize(12);
    doc.setTextColor(branding.primaryColor);
    doc.text(t.teacherFeedback, margin, y);
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor('#0f172a');
    for (const f of feedback) {
      const wrapped = doc.splitTextToSize(
        `· ${f.feedback.slice(0, 220)}`,
        textW,
      );
      doc.text(wrapped, margin + 2, y);
      y += wrapped.length * 4 + 2;
      if (y > 270) {
        doc.addPage();
        renderBrandedHeader(doc, branding);
        y = 40;
      }
    }
    y += 4;
  }

  // Suggestion
  doc.setFontSize(12);
  doc.setTextColor(branding.primaryColor);
  doc.text(t.nextSteps, margin, y);
  y += 6;
  doc.setFontSize(10);
  doc.setTextColor('#0f172a');
  const conceptsCount = kid.conceptsLearned?.length ?? 0;
  const suggestion = doc.splitTextToSize(t.suggestion(conceptsCount), textW);
  doc.text(suggestion, margin, y);
  y += suggestion.length * 4 + 6;

  // Footer
  doc.setFontSize(8);
  doc.setTextColor('#94a3b8');
  doc.text(t.footer, margin, 290);

  return {
    pdf: Buffer.from(doc.output('arraybuffer')),
    kidName: kid.name,
  };
}
