/**
 * GET /api/hpc/[id]/export?kidId=&term=
 *
 * Generates a CBSE-template HPC PDF for one student × one term. Uses
 * the school-branding pipeline so logo + letterhead + colors flow
 * through. Teacher / schoolAdmin gated.
 *
 * Note: `[id]` is currently redundant with the query params; it's
 * retained so future routes can migrate to REST-shaped URLs without
 * changing callers.
 */

import { NextRequest, NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';
import { handleApiError, AppException } from '@/lib/api-utils';
import { requireRole } from '@/lib/auth-utils';
import { adminDb } from '@gsi/firebase/admin';
import { getHpcNarrative } from '@gsi/firebase/schoolService';
import {
  getSchoolBranding,
  renderBrandedHeader,
} from '@/lib/pdf/schoolBranding';

export async function GET(
  request: NextRequest,
  _ctx: { params: { id: string } },
) {
  try {
    const auth = await requireRole(request, ['teacher', 'schoolAdmin']);
    if (!auth.schoolId) {
      throw new AppException('FORBIDDEN', 'Teacher is not attached to a school.', 403);
    }
    const url = new URL(request.url);
    const kidId = url.searchParams.get('kidId');
    const term = url.searchParams.get('term');
    if (!kidId || !term) {
      throw new AppException('INVALID_INPUT', 'kidId and term are required.', 400);
    }

    const kidSnap = await adminDb.collection('kids').doc(kidId).get();
    if (!kidSnap.exists) {
      throw new AppException('NOT_FOUND', 'Student not found.', 404);
    }
    if (kidSnap.data()?.schoolId !== auth.schoolId) {
      throw new AppException('FORBIDDEN', 'Student is not in your school.', 403);
    }
    const kid = kidSnap.data() as Record<string, unknown>;
    const kidName = (kid.name as string) ?? 'Student';
    const grade = (kid.grade as string) ?? '—';

    const narrative = await getHpcNarrative(auth.schoolId, kidId, term);
    if (!narrative) {
      throw new AppException('NOT_FOUND', 'No HPC narrative on file for this student and term.', 404);
    }

    const branding = await getSchoolBranding(auth.schoolId);

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    renderBrandedHeader(doc, branding);

    // Meta strip
    doc.setFontSize(10);
    doc.setTextColor('#475569');
    doc.text(
      `Holistic Progress Card · ${term}  ·  Class ${grade}`,
      14,
      34,
    );

    // Student name
    doc.setFontSize(14);
    doc.setTextColor('#0f172a');
    doc.text(kidName, 14, 46);

    const margin = 14;
    const pageWidth = doc.internal.pageSize.getWidth();
    const textWidth = pageWidth - margin * 2;

    const sections: Array<{ title: string; body: string }> = [
      { title: 'Cognitive Domain', body: narrative.cognitive },
      { title: 'Affective Domain', body: narrative.affective },
      { title: 'Psychomotor Domain', body: narrative.psychomotor },
    ];
    if (narrative.nextTermFocus) {
      sections.push({ title: 'Next-Term Focus', body: narrative.nextTermFocus });
    }

    let y = 58;
    for (const s of sections) {
      if (y > 260) {
        doc.addPage();
        renderBrandedHeader(doc, branding);
        y = 40;
      }
      doc.setFontSize(12);
      doc.setTextColor(branding.primaryColor);
      doc.text(s.title, margin, y);
      y += 6;
      doc.setFontSize(11);
      doc.setTextColor('#111827');
      const wrapped = doc.splitTextToSize(s.body, textWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5 + 6;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor('#94a3b8');
    doc.text(
      `Generated by ${branding.schoolName} via GSI AI Studio · Draft reviewed by teacher.`,
      margin,
      290,
    );

    const buffer = Buffer.from(doc.output('arraybuffer'));
    return new NextResponse(buffer as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="hpc-${term}-${kidName.replace(/\s+/g, '_')}.pdf"`,
      },
    });
  } catch (error) {
    return handleApiError(error);
  }
}
