import jsPDF from 'jspdf';
import {
  getConcept,
  CURRICULUM_CATEGORIES,
  type CurriculumCategory,
  getAllConcepts,
} from '@/lib/curriculum/curriculumMap';
import type {
  AssignmentDoc,
  ClassDoc,
  SchoolDoc,
  SubmissionDoc,
} from '@gsi/types';

/**
 * Input shape for the compliance report. All data is pre-fetched and passed
 * in — this module is pure presentation so it runs cleanly on both the
 * server (Netlify Functions) and the client.
 */
export interface ComplianceReportInput {
  school: SchoolDoc;
  classes: ClassDoc[];
  assignments: AssignmentDoc[];
  submissions: SubmissionDoc[];
  students: Array<{
    id: string;
    name: string;
    grade?: string;
    totalCreations: number;
    conceptsLearned: string[];
  }>;
  dateRange?: { start: Date; end: Date };
}

const A4_WIDTH = 210;
const MARGIN = 15;
const CONTENT_WIDTH = A4_WIDTH - MARGIN * 2;
const BRAND_PURPLE = '#7C3AED';
const BRAND_TEXT = '#1F2937';
const BRAND_GRAY = '#6B7280';

function ensureSpace(doc: jsPDF, y: number, min = 40): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y > pageH - min) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function sectionHeader(doc: jsPDF, title: string, y: number): number {
  y = ensureSpace(doc, y, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(BRAND_PURPLE);
  doc.text(title, MARGIN, y);
  doc.setDrawColor(BRAND_PURPLE);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y + 1.5, MARGIN + CONTENT_WIDTH, y + 1.5);
  return y + 7;
}

function kv(doc: jsPDF, label: string, value: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(BRAND_GRAY);
  doc.text(label.toUpperCase(), MARGIN, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(BRAND_TEXT);
  doc.text(value, MARGIN + 55, y);
  return y + 6;
}

function paragraph(doc: jsPDF, text: string, y: number): number {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(BRAND_TEXT);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
  for (const line of lines) {
    y = ensureSpace(doc, y);
    doc.text(line, MARGIN, y);
    y += 5;
  }
  return y + 2;
}

/**
 * Build a compliance report from the given input data. Returns a `jsPDF`
 * instance the caller can serialize (`.output('blob')`, `.save()`, etc.).
 *
 * Callers:
 *   - ADMIN-002 per-class export (from teacher dashboard)
 *   - ADMIN-003 school-wide export (from school admin dashboard)
 */
export function buildComplianceReport(input: ComplianceReportInput): jsPDF {
  const { school, classes, assignments, submissions, students, dateRange } = input;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN;

  // Letterhead
  doc.setFillColor(BRAND_PURPLE);
  doc.rect(0, 0, A4_WIDTH, 20, 'F');
  doc.setTextColor('#FFFFFF');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('CBSE AI & CT Compliance Report', MARGIN, 13);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by GSI AI Studio', A4_WIDTH - MARGIN, 13, { align: 'right' });

  y = 28;

  // School info
  y = sectionHeader(doc, 'School', y);
  y = kv(doc, 'Name', school.name, y);
  y = kv(doc, 'Board', school.board.toUpperCase(), y);
  y = kv(doc, 'Location', `${school.city}, ${school.state}`, y);
  y = kv(doc, 'Students', String(school.studentCount), y);
  y = kv(doc, 'Teachers', String(school.teacherIds.length), y);
  if (dateRange) {
    y = kv(
      doc,
      'Period',
      `${dateRange.start.toLocaleDateString()} – ${dateRange.end.toLocaleDateString()}`,
      y,
    );
  }
  y += 2;

  // Summary metrics
  y = sectionHeader(doc, 'Summary', y);
  const totalSubmissions = submissions.length;
  const approvedSubmissions = submissions.filter((s) => s.status === 'approved').length;
  const completionRate =
    assignments.length > 0 && students.length > 0
      ? Math.round((totalSubmissions / (assignments.length * students.length)) * 100)
      : 0;
  y = kv(doc, 'Classes', String(classes.length), y);
  y = kv(doc, 'Assignments', String(assignments.length), y);
  y = kv(doc, 'Submissions', String(totalSubmissions), y);
  y = kv(doc, 'Approved', String(approvedSubmissions), y);
  y = kv(doc, 'Completion rate', `${completionRate}%`, y);
  y += 2;

  // Curriculum coverage
  y = sectionHeader(doc, 'Curriculum coverage', y);
  const conceptStudentExposure = computeConceptExposure(
    assignments,
    submissions,
    students,
  );
  const categories: CurriculumCategory[] = [
    'ai_basics',
    'ml_concepts',
    'ethics',
    'applications',
    'ct_skills',
  ];
  for (const cat of categories) {
    const catConcepts = getAllConcepts().filter((c) => c.category === cat);
    if (catConcepts.length === 0) continue;
    y = ensureSpace(doc, y, 25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(BRAND_TEXT);
    doc.text(CURRICULUM_CATEGORIES[cat].label, MARGIN, y);
    y += 5;
    for (const concept of catConcepts) {
      const exposed = conceptStudentExposure.get(concept.id) ?? 0;
      const pct =
        students.length > 0 ? Math.round((exposed / students.length) * 100) : 0;
      y = ensureSpace(doc, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(BRAND_TEXT);
      doc.text(`• ${concept.name}`, MARGIN + 3, y);
      doc.text(`${exposed}/${students.length}`, MARGIN + 90, y);
      doc.text(`${pct}%`, MARGIN + 120, y);
      // Simple bar
      const barStart = MARGIN + 135;
      const barMax = 50;
      doc.setFillColor('#E5E7EB');
      doc.rect(barStart, y - 3, barMax, 3, 'F');
      if (pct > 0) {
        doc.setFillColor(BRAND_PURPLE);
        doc.rect(barStart, y - 3, Math.round((pct / 100) * barMax), 3, 'F');
      }
      y += 5;
    }
    y += 2;
  }

  // Per-student participation
  y = sectionHeader(doc, 'Per-student participation', y);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(BRAND_GRAY);
  doc.text('Student', MARGIN, y);
  doc.text('Grade', MARGIN + 80, y);
  doc.text('Creations', MARGIN + 110, y);
  doc.text('Concepts', MARGIN + 150, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(BRAND_TEXT);
  for (const s of students.slice(0, 120)) {
    y = ensureSpace(doc, y);
    doc.text(truncate(s.name, 38), MARGIN, y);
    doc.text(s.grade ?? '—', MARGIN + 80, y);
    doc.text(String(s.totalCreations), MARGIN + 110, y);
    doc.text(String(s.conceptsLearned.length), MARGIN + 150, y);
    y += 4.5;
  }
  if (students.length > 120) {
    y += 2;
    doc.setTextColor(BRAND_GRAY);
    doc.text(`+${students.length - 120} more students…`, MARGIN, y);
    y += 5;
  }

  // Assignment list
  y += 4;
  y = sectionHeader(doc, 'Assignments', y);
  if (assignments.length === 0) {
    y = paragraph(doc, 'No assignments in the selected period.', y);
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(BRAND_GRAY);
    doc.text('Title', MARGIN, y);
    doc.text('Type', MARGIN + 95, y);
    doc.text('Due', MARGIN + 120, y);
    doc.text('Subs', MARGIN + 150, y);
    doc.text('Tags', MARGIN + 170, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(BRAND_TEXT);
    for (const a of assignments) {
      y = ensureSpace(doc, y);
      doc.text(truncate(a.title, 50), MARGIN, y);
      doc.text(a.creationType, MARGIN + 95, y);
      doc.text(a.dueDate.toLocaleDateString(), MARGIN + 120, y);
      doc.text(String(a.submissions ?? 0), MARGIN + 150, y);
      doc.text(String((a.curriculumTags ?? []).length), MARGIN + 170, y);
      y += 4.5;
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(BRAND_GRAY);
    doc.text(
      `${school.name} · CBSE AI compliance · Page ${i} of ${pageCount}`,
      A4_WIDTH / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' },
    );
  }

  return doc;
}

/**
 * For each concept id, count the number of distinct students who have been
 * exposed to it. A student is considered "exposed" if they have the concept
 * id in their `conceptsLearned` field, OR they submitted a creation to an
 * assignment tagged with that concept.
 */
function computeConceptExposure(
  assignments: AssignmentDoc[],
  submissions: SubmissionDoc[],
  students: ComplianceReportInput['students'],
): Map<string, number> {
  const exposure = new Map<string, Set<string>>();

  // From direct conceptsLearned on the kid doc
  for (const student of students) {
    for (const concept of student.conceptsLearned) {
      if (!getConcept(concept)) continue;
      if (!exposure.has(concept)) exposure.set(concept, new Set());
      exposure.get(concept)!.add(student.id);
    }
  }

  // From assignment tags (via their submissions)
  const tagsByAssignment = new Map(assignments.map((a) => [a.id, a.curriculumTags]));
  for (const sub of submissions) {
    const tags = tagsByAssignment.get(sub.assignmentId) ?? [];
    for (const tagId of tags) {
      if (!getConcept(tagId)) continue;
      if (!exposure.has(tagId)) exposure.set(tagId, new Set());
      exposure.get(tagId)!.add(sub.kidId);
    }
  }

  const out = new Map<string, number>();
  for (const [concept, studentSet] of exposure) {
    out.set(concept, studentSet.size);
  }
  return out;
}

function truncate(str: string, max: number): string {
  if (str.length <= max) return str;
  return `${str.slice(0, max - 1)}…`;
}

/**
 * Convenience wrapper for browser download flows.
 */
export async function downloadComplianceReport(
  input: ComplianceReportInput,
  filename: string,
): Promise<void> {
  const doc = buildComplianceReport(input);
  doc.save(filename);
}
