import { NextRequest } from 'next/server';
import { apiSuccess, handleApiError, AppException } from '@/lib/api-utils';
import { musicInputSchema } from '@/lib/validators';
import { filterInput, filterOutput } from '@/lib/safety/inputFilter';
import { checkRateLimit, trackCreation, enforceIpRateLimit } from '@/lib/firebase/sessionService';
import { saveCreation } from '@/lib/firebase/creationService';
import { generateJsonWithClaude } from '@/lib/ai/claudeClient';
import { generateJsonWithGroq } from '@/lib/ai/groqClient';
import { generateMusic } from '@/lib/ai/musicClient';
import { uploadBuffer, attachAssetToParent } from '@/lib/storage/assetService';
import { MUSIC_SYSTEM_PROMPT, buildMusicUserPrompt } from '@/lib/ai/prompts/musicPrompt';
import type { AiXrayData, MusicContent } from '@/types';

/** Shape returned by LLM for music metadata */
interface LlmMusicResponse {
  title: string;
  lyrics: string;
  bpm: number;
  styleDescription: string;
  aiXray: {
    concept: string;
    explanation: string;
    curriculumTag: string;
  };
}

// Auto-detect which LLM to use based on available API keys
function shouldUseGroq(): boolean {
  return !!process.env.GROQ_API_KEY && !process.env.ANTHROPIC_API_KEY?.startsWith('sk-ant-api');
}

/**
 * POST /api/ai/music
 * Generate a song using LLM (lyrics/metadata) + music generator (audio).
 * See: docs/api-contracts.md#post-apiaimusic
 */
export async function POST(request: NextRequest) {
  try {
    // 1. Validate session
    const sessionId = request.headers.get('X-Session-Id');
    if (!sessionId) {
      throw new AppException('UNAUTHORIZED', 'Missing session', 401);
    }

    // 2. Parse and validate input
    const body = await request.json();
    const input = musicInputSchema.parse(body);

    // 3. Safety filter
    if (input.theme) filterInput(input.theme);
    if (input.lyricsPrompt) filterInput(input.lyricsPrompt);

    // 4. Check rate limit (IP first, then per-session)
    const ipAddress =
      request.headers.get('x-nf-client-connection-ip') ??
      request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
      null;
    await enforceIpRateLimit(ipAddress);
    await checkRateLimit(sessionId);

    // 5. Generate music metadata via LLM
    const generateJson = shouldUseGroq() ? generateJsonWithGroq : generateJsonWithClaude;
    const llmResponse = await generateJson<LlmMusicResponse>({
      systemPrompt: MUSIC_SYSTEM_PROMPT,
      userMessage: buildMusicUserPrompt({
        mood: input.mood,
        genre: input.genre,
        theme: input.theme,
        duration: input.duration,
        instruments: input.instruments,
        lyricsPrompt: input.lyricsPrompt,
        ageGroup: input.ageGroup,
      }),
      maxTokens: 2048,
    });

    // 6. Safety-filter LLM output
    const filteredLyrics = filterOutput(llmResponse.lyrics);
    const filteredStyle = filterOutput(llmResponse.styleDescription);

    // 7. Generate audio via music client
    const musicResult = await generateMusic({
      styleDescription: filteredStyle,
      duration: input.duration,
      mood: input.mood,
      genre: input.genre,
      bpm: llmResponse.bpm,
    });

    // 8. Build music content
    const modelName = shouldUseGroq() ? 'llama-3.3-70b' : 'claude-sonnet';
    console.log(`[Music] LLM: ${modelName}, Audio: ${musicResult.provider}`);

    // 8a. Persist the audio to the assets layer (PERF-001).
    //     Music tracks generated by Lyria are PCM/WAV data URIs which Firestore
    //     can't store; the assets layer puts them on object storage and we
    //     reference by ID. Replicate gives us an external URL — we still rehost
    //     so the creation works after Replicate's URL expires.
    let audioAssetId: string | undefined;
    let publicAudioUrl: string = musicResult.audioUrl;
    try {
      const buffer = await audioUrlToBuffer(musicResult.audioUrl);
      const { mimeType } = detectAudioFormat(musicResult.audioUrl);
      const asset = await uploadBuffer({
        buffer,
        kind: 'audio',
        mimeType,
        sourceType: 'ai_generated',
        parentRefType: 'creation',
        ownerSessionId: sessionId,
        durationSec: musicResult.duration,
        visibility: 'public', // music creations default to public-readable URL
      });
      audioAssetId = asset.id;
      publicAudioUrl = asset.publicUrl;
    } catch (err) {
      // Persistence is best-effort — if the asset upload fails we still return
      // the in-memory data URI so the kid hears their song this session.
      console.warn(
        '[Music] Asset persistence failed, falling through to in-memory URL:',
        err instanceof Error ? err.message : err,
      );
    }

    const musicContent: MusicContent & { title: string; waveformData: number[] } = {
      title: llmResponse.title,
      audioAssetId,
      audioUrl: publicAudioUrl,
      duration: musicResult.duration,
      lyrics: filteredLyrics,
      bpm: llmResponse.bpm,
      genre: input.genre,
      mood: input.mood,
      instruments: input.instruments ?? [],
      waveformData: musicResult.waveformData,
    };

    // 9. Build AI X-Ray metadata
    const aiXray: AiXrayData = {
      model: modelName,
      concept: llmResponse.aiXray.concept,
      explanation: llmResponse.aiXray.explanation,
      curriculumTag: llmResponse.aiXray.curriculumTag,
      aiPoints: 15,
    };

    // 10. Save creation to Firestore
    //     Strip the audioUrl if it's still a data URI (asset persistence
    //     failed) — Firestore has a 1MB doc limit and base64 PCM is huge.
    const isDataUri = publicAudioUrl.startsWith('data:');
    const savableContent: Record<string, unknown> = {
      title: musicContent.title,
      audioAssetId,
      duration: musicContent.duration,
      genre: musicContent.genre,
      mood: musicContent.mood,
      lyrics: musicContent.lyrics,
      instruments: musicContent.instruments,
      bpm: musicContent.bpm,
    };
    if (!isDataUri) savableContent.audioUrl = publicAudioUrl;

    const { id: creationId, shareUrl } = await saveCreation({
      type: 'music',
      title: llmResponse.title,
      prompt: input.theme ?? `${input.mood} ${input.genre}`,
      content: savableContent,
      media: isDataUri
        ? []
        : [{ url: publicAudioUrl, type: 'audio/mpeg', alt: `${llmResponse.title} audio` }],
      aiMetadata: aiXray as unknown as Record<string, unknown>,
      aiConceptsTaught: ['generative_ai', 'text_to_music', 'pattern_recognition_audio'],
      sessionId,
      remixedFromId: input.remixedFromId,
    });

    // 10a. Link the asset to the creation now that we have an ID.
    if (audioAssetId) {
      await attachAssetToParent(audioAssetId, 'creation', creationId).catch(() => undefined);
    }

    // 11. Track creation for rate limiting
    await trackCreation(sessionId);

    return apiSuccess({ music: musicContent, aiXray, creationId, shareUrl });
  } catch (error) {
    return handleApiError(error);
  }
}

// ─────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────

/** Convert a data URI or external URL into a Buffer for asset upload. */
async function audioUrlToBuffer(url: string): Promise<Buffer> {
  if (url.startsWith('data:')) {
    const commaIdx = url.indexOf(',');
    if (commaIdx === -1) throw new Error('Invalid data URI');
    const meta = url.slice(5, commaIdx); // strip "data:"
    const payload = url.slice(commaIdx + 1);
    if (meta.includes(';base64')) {
      return Buffer.from(payload, 'base64');
    }
    return Buffer.from(decodeURIComponent(payload), 'utf-8');
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch audio: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

/** Best-effort MIME-type detection from URL or data URI metadata. */
function detectAudioFormat(url: string): { mimeType: string } {
  if (url.startsWith('data:')) {
    const m = url.match(/^data:([^;,]+)/);
    if (m && m[1]) return { mimeType: m[1] };
  }
  if (url.endsWith('.mp3')) return { mimeType: 'audio/mpeg' };
  if (url.endsWith('.wav')) return { mimeType: 'audio/wav' };
  if (url.endsWith('.ogg')) return { mimeType: 'audio/ogg' };
  if (url.endsWith('.webm')) return { mimeType: 'audio/webm' };
  return { mimeType: 'audio/mpeg' }; // sensible default for Replicate output
}
