import Replicate from 'replicate';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface MusicGenOptions {
  styleDescription: string;
  duration: number; // 15-60 seconds
  mood: string;
  genre: string;
  bpm?: number;
}

export interface MusicGenResult {
  audioUrl: string;       // base64 data URI or external URL
  duration: number;       // actual duration in seconds
  waveformData: number[]; // 50 data points, 0-1
  provider: string;       // which provider was used
}

// ---------------------------------------------------------------------------
// Provider detection
// ---------------------------------------------------------------------------

function shouldUseLyria(): boolean {
  return !!process.env.GEMINI_API_KEY;
}

function shouldUseReplicate(): boolean {
  const token = process.env.REPLICATE_API_TOKEN;
  return !!token && !token.includes('your-token');
}

// ---------------------------------------------------------------------------
// Lyria RealTime (Google — free, GEMINI_API_KEY)
// ---------------------------------------------------------------------------

async function generateWithLyria(opts: MusicGenOptions): Promise<MusicGenResult> {
  const { GoogleGenAI } = await import('@google/genai');
  type LyriaMsgType = import('@google/genai').LiveMusicServerMessage;

  const client = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY!,
  });

  // Collect base64 PCM chunks via onmessage callback
  const pcmBase64Chunks: string[] = [];
  const durationMs = opts.duration * 1000;
  let setupDone = false;

  const session = await client.live.music.connect({
    model: 'models/lyria-realtime-exp',
    callbacks: {
      onmessage: (msg: LyriaMsgType) => {
        if (msg.setupComplete) {
          setupDone = true;
          return;
        }
        const chunk = msg.audioChunk;
        if (chunk?.data) {
          pcmBase64Chunks.push(chunk.data);
        }
      },
      onerror: (e: ErrorEvent) => {
        console.warn('[Lyria] WebSocket error:', e.error);
      },
    },
  });

  // Wait for setup to complete
  await new Promise<void>((resolve) => {
    if (setupDone) { resolve(); return; }
    const check = setInterval(() => {
      if (setupDone) { clearInterval(check); resolve(); }
    }, 50);
    // Timeout after 10s
    setTimeout(() => { clearInterval(check); resolve(); }, 10000);
  });

  // Configure and start
  const promptText = `${opts.mood} ${opts.genre} music. ${opts.styleDescription}`;

  await session.setWeightedPrompts({
    weightedPrompts: [{ text: promptText, weight: 1.0 }],
  });

  await session.setMusicGenerationConfig({
    musicGenerationConfig: {
      bpm: opts.bpm ?? 120,
      temperature: 1.0,
    },
  });

  session.play();

  // Buffer audio for the requested duration
  await new Promise<void>((resolve) => {
    setTimeout(resolve, durationMs);
  });

  session.stop();

  // Small delay to collect any remaining chunks
  await new Promise<void>((resolve) => setTimeout(resolve, 500));

  // Combine base64 chunks into a single PCM buffer
  const pcmBuffer = Buffer.concat(
    pcmBase64Chunks.map((b64) => Buffer.from(b64, 'base64'))
  );

  if (pcmBuffer.length === 0) {
    throw new Error('No audio data received from Lyria');
  }

  // Generate waveform from PCM amplitudes (16-bit samples)
  const waveformData = extractWaveform(pcmBuffer, 50);

  // Encode as WAV data URI (Lyria outputs 48kHz stereo 16-bit PCM)
  const wavBuffer = encodeWav(pcmBuffer, 48000, 2);
  const audioUrl = `data:audio/wav;base64,${wavBuffer.toString('base64')}`;

  return {
    audioUrl,
    duration: opts.duration,
    waveformData,
    provider: 'lyria-realtime',
  };
}

// ---------------------------------------------------------------------------
// Replicate MusicGen (paid, REPLICATE_API_TOKEN)
// ---------------------------------------------------------------------------

async function generateWithReplicate(opts: MusicGenOptions): Promise<MusicGenResult> {
  const token = process.env.REPLICATE_API_TOKEN;
  if (!token) throw new Error('REPLICATE_API_TOKEN not set');

  const replicate = new Replicate({ auth: token });

  const prompt = `${opts.mood} ${opts.genre} music. ${opts.styleDescription}`;

  const output = await replicate.run(
    'meta/musicgen:b05b1dff1d8c6dc63d14b0cdb42135571e441e36e3f16c62a8824f0abc5f5571',
    {
      input: {
        prompt,
        duration: Math.min(opts.duration, 30), // MusicGen max ~30s
        model_version: 'stereo-melody-large',
        output_format: 'mp3',
        normalization_strategy: 'peak',
      },
    },
  );

  const audioUrl = output as unknown as string;
  if (!audioUrl) throw new Error('No audio generated by Replicate');

  // Fetch audio and convert to base64 for consistent handling
  const res = await fetch(audioUrl);
  if (!res.ok) throw new Error(`Failed to fetch audio: ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const base64Url = `data:audio/mpeg;base64,${buffer.toString('base64')}`;

  return {
    audioUrl: base64Url,
    duration: opts.duration,
    waveformData: synthesizeWaveform(50),
    provider: 'replicate-musicgen',
  };
}

// ---------------------------------------------------------------------------
// Mock fallback (always works, no external dependencies)
// ---------------------------------------------------------------------------

function generateMusicMock(opts: MusicGenOptions): MusicGenResult {
  console.log(`[Music] Mock provider — generating placeholder for: ${opts.mood} ${opts.genre}`);

  // Generate a minimal valid WAV file (silence with slight noise for waveform)
  const sampleRate = 44100;
  const numChannels = 2;
  const durationSec = Math.min(opts.duration, 5); // Keep mock short
  const numSamples = sampleRate * durationSec;
  const bytesPerSample = 2; // 16-bit

  // Generate very quiet noise so the audio element initializes properly
  const pcmData = Buffer.alloc(numSamples * numChannels * bytesPerSample);
  for (let i = 0; i < numSamples * numChannels; i++) {
    const sample = Math.floor((Math.random() - 0.5) * 200); // very quiet
    pcmData.writeInt16LE(sample, i * 2);
  }

  const wavBuffer = encodeWav(pcmData, sampleRate, numChannels);
  const audioUrl = `data:audio/wav;base64,${wavBuffer.toString('base64')}`;

  return {
    audioUrl,
    duration: durationSec,
    waveformData: synthesizeWaveform(50),
    provider: 'mock',
  };
}

// ---------------------------------------------------------------------------
// Main export — provider chain with fallthrough
// ---------------------------------------------------------------------------

export async function generateMusic(opts: MusicGenOptions): Promise<MusicGenResult> {
  // Try Lyria first (free)
  if (shouldUseLyria()) {
    try {
      console.log('[Music] Using provider: lyria-realtime');
      return await generateWithLyria(opts);
    } catch (err) {
      console.warn('[Music] Lyria failed, falling through:', err instanceof Error ? err.message : err);
    }
  }

  // Try Replicate (paid)
  if (shouldUseReplicate()) {
    try {
      console.log('[Music] Using provider: replicate-musicgen');
      return await generateWithReplicate(opts);
    } catch (err) {
      console.warn('[Music] Replicate failed, falling through:', err instanceof Error ? err.message : err);
    }
  }

  // Always-works fallback
  console.log('[Music] Using provider: mock');
  return generateMusicMock(opts);
}

// ---------------------------------------------------------------------------
// Audio utility helpers
// ---------------------------------------------------------------------------

/** Extract waveform data (0-1 amplitude) from 16-bit PCM buffer */
function extractWaveform(pcmBuffer: Buffer, numPoints: number): number[] {
  const samples = pcmBuffer.length / 2; // 16-bit = 2 bytes per sample
  const chunkSize = Math.max(1, Math.floor(samples / numPoints));
  const waveform: number[] = [];

  for (let i = 0; i < numPoints; i++) {
    const start = i * chunkSize;
    let maxAmp = 0;
    for (let j = 0; j < chunkSize && (start + j) * 2 + 1 < pcmBuffer.length; j++) {
      const sample = Math.abs(pcmBuffer.readInt16LE((start + j) * 2));
      if (sample > maxAmp) maxAmp = sample;
    }
    waveform.push(Math.min(1, maxAmp / 32768));
  }

  return waveform;
}

/** Generate synthetic waveform when real PCM data isn't available */
function synthesizeWaveform(numPoints: number): number[] {
  return Array.from({ length: numPoints }, (_, i) => {
    const base = Math.abs(Math.sin((i * Math.PI) / 12));
    const variation = Math.random() * 0.3;
    return Math.min(1, Math.max(0.05, base * 0.7 + variation));
  });
}

/** Encode raw PCM data as a WAV file buffer */
function encodeWav(pcmData: Buffer, sampleRate: number, numChannels: number): Buffer {
  const bytesPerSample = 2; // 16-bit
  const blockAlign = numChannels * bytesPerSample;
  const byteRate = sampleRate * blockAlign;
  const dataSize = pcmData.length;
  const headerSize = 44;

  const buffer = Buffer.alloc(headerSize + dataSize);

  // RIFF header
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);

  // fmt sub-chunk
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);           // sub-chunk size
  buffer.writeUInt16LE(1, 20);            // PCM format
  buffer.writeUInt16LE(numChannels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bytesPerSample * 8, 34); // bits per sample

  // data sub-chunk
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);
  pcmData.copy(buffer, headerSize);

  return buffer;
}
