import { AppException } from '@/lib/api-utils';
import type { GameScene } from '@/types/creation.types';

/**
 * Validate and prune a scene graph generated by the LLM.
 * Returns only reachable scenes. Throws AppException if the graph is invalid.
 */
export function validateSceneGraph(scenes: GameScene[], startSceneId: string): GameScene[] {
  const sceneMap = new Map(scenes.map((s) => [s.id, s]));

  // 1. startSceneId must exist
  if (!sceneMap.has(startSceneId)) {
    throw new AppException('AI_ERROR', 'Invalid game: start scene not found', 500);
  }

  // 2. All nextSceneId references must be valid
  for (const scene of scenes) {
    for (const choice of scene.choices) {
      if (!sceneMap.has(choice.nextSceneId)) {
        throw new AppException(
          'AI_ERROR',
          `Invalid game: scene "${scene.id}" references non-existent scene "${choice.nextSceneId}"`,
          500
        );
      }
    }
  }

  // 3. Ending scenes must have empty choices; non-ending scenes must have choices
  for (const scene of scenes) {
    if (scene.isEnding && scene.choices.length > 0) {
      throw new AppException('AI_ERROR', `Invalid game: ending scene "${scene.id}" has choices`, 500);
    }
    if (!scene.isEnding && scene.choices.length === 0) {
      throw new AppException('AI_ERROR', `Invalid game: non-ending scene "${scene.id}" has no choices`, 500);
    }
  }

  // 4. BFS reachability from startSceneId — prune unreachable scenes
  const visited = new Set<string>();
  const queue = [startSceneId];
  while (queue.length > 0) {
    const id = queue.shift()!;
    if (visited.has(id)) continue;
    visited.add(id);
    const scene = sceneMap.get(id)!;
    for (const choice of scene.choices) {
      queue.push(choice.nextSceneId);
    }
  }

  const reachableScenes = scenes.filter((s) => visited.has(s.id));
  const unreachable = scenes.filter((s) => !visited.has(s.id));
  if (unreachable.length > 0) {
    console.warn(
      `[Game] Pruned ${unreachable.length} unreachable scene(s): ${unreachable.map((s) => s.id).join(', ')}`
    );
  }

  // 5. At least one ending must be reachable
  const reachableEndings = reachableScenes.filter((s) => s.isEnding);
  if (reachableEndings.length === 0) {
    throw new AppException('AI_ERROR', 'Invalid game: no reachable ending scenes', 500);
  }

  // 6. Every reachable non-ending scene must have a path to at least one ending
  //    (detects cycles and dead-end branches that never terminate)
  const canReachEnding = new Map<string, boolean>();

  // Endings trivially reach an ending
  for (const scene of reachableScenes) {
    if (scene.isEnding) canReachEnding.set(scene.id, true);
  }

  function checkCanReachEnding(sceneId: string, visiting: Set<string>): boolean {
    if (canReachEnding.has(sceneId)) return canReachEnding.get(sceneId)!;
    if (visiting.has(sceneId)) return false; // cycle detected

    visiting.add(sceneId);
    const scene = sceneMap.get(sceneId)!;
    const reachable = scene.choices.some((c) => checkCanReachEnding(c.nextSceneId, visiting));
    visiting.delete(sceneId);

    canReachEnding.set(sceneId, reachable);
    return reachable;
  }

  for (const scene of reachableScenes) {
    if (!scene.isEnding && !checkCanReachEnding(scene.id, new Set())) {
      throw new AppException(
        'AI_ERROR',
        `Invalid game: scene "${scene.id}" has no path to any ending (stuck in cycle or dead end)`,
        500
      );
    }
  }

  return reachableScenes;
}
