import { AppException } from '@/lib/api-utils';
import type { GameScene } from '@/types/creation.types';

/**
 * Validate a scene graph generated by the LLM.
 * Throws AppException if the graph is invalid.
 */
export function validateSceneGraph(scenes: GameScene[], startSceneId: string): void {
  const sceneMap = new Map(scenes.map((s) => [s.id, s]));

  // 1. startSceneId must exist
  if (!sceneMap.has(startSceneId)) {
    throw new AppException('AI_ERROR', 'Invalid game: start scene not found', 500);
  }

  // 2. All nextSceneId references must be valid
  for (const scene of scenes) {
    for (const choice of scene.choices) {
      if (!sceneMap.has(choice.nextSceneId)) {
        throw new AppException(
          'AI_ERROR',
          `Invalid game: scene "${scene.id}" references non-existent scene "${choice.nextSceneId}"`,
          500
        );
      }
    }
  }

  // 3. Ending scenes must have empty choices; non-ending scenes must have choices
  for (const scene of scenes) {
    if (scene.isEnding && scene.choices.length > 0) {
      throw new AppException('AI_ERROR', `Invalid game: ending scene "${scene.id}" has choices`, 500);
    }
    if (!scene.isEnding && scene.choices.length === 0) {
      throw new AppException('AI_ERROR', `Invalid game: non-ending scene "${scene.id}" has no choices`, 500);
    }
  }

  // 4. BFS reachability from startSceneId — warn-only (don't throw) for unreachable scenes
  const visited = new Set<string>();
  const queue = [startSceneId];
  while (queue.length > 0) {
    const id = queue.shift()!;
    if (visited.has(id)) continue;
    visited.add(id);
    const scene = sceneMap.get(id)!;
    for (const choice of scene.choices) {
      queue.push(choice.nextSceneId);
    }
  }

  const unreachable = scenes.filter((s) => !visited.has(s.id));
  if (unreachable.length > 0) {
    console.warn(
      `[Game] Unreachable scenes detected: ${unreachable.map((s) => s.id).join(', ')}. Removing them.`
    );
  }

  // 5. At least one ending must be reachable
  const reachableEndings = scenes.filter((s) => s.isEnding && visited.has(s.id));
  if (reachableEndings.length === 0) {
    throw new AppException('AI_ERROR', 'Invalid game: no reachable ending scenes', 500);
  }
}
