import {
  LayoutDashboard,
  GraduationCap,
  FileText,
  ClipboardList,
  Users,
  BookOpen,
  Inbox,
  Settings,
  HelpCircle,
} from 'lucide-react';
import type { DashboardConfig } from '@gsi/types';

export const teacherDashboardConfig: DashboardConfig = {
  role: 'teacher',
  brand: {
    name: 'GSI for Teachers',
    href: '/teacher',
    logoSrc: '/images/gsi-logo.svg',
  },
  sidebar: {
    primary: [
      {
        id: 'home',
        label: 'Dashboard',
        href: '/teacher',
        icon: LayoutDashboard,
        match: (p) => p === '/teacher',
      },
      {
        id: 'classes',
        label: 'Classes',
        href: '/teacher',
        icon: Users,
        match: (p) => p.startsWith('/teacher/classes'),
      },
      {
        id: 'lessons',
        label: 'Lesson Plans',
        href: '/teacher/lessons',
        icon: GraduationCap,
        match: (p) => p === '/teacher/lessons',
      },
      {
        id: 'papers',
        label: 'Question Papers',
        href: '/teacher/papers',
        icon: FileText,
        match: (p) => p === '/teacher/papers',
      },
      {
        id: 'curriculum',
        label: 'Curriculum',
        href: '/teacher/curriculum',
        icon: BookOpen,
        match: (p) => p.startsWith('/teacher/curriculum'),
      },
      {
        id: 'notifications',
        label: 'Notifications',
        href: '/notifications',
        icon: Inbox,
        match: (p) => p === '/notifications',
      },
    ],
    secondary: [
      {
        id: 'usage',
        label: 'AI Usage',
        href: '/admin/usage',
        icon: ClipboardList,
      },
      { id: 'help', label: 'Help', href: '/help', icon: HelpCircle },
      { id: 'settings', label: 'Settings', href: '/school/settings', icon: Settings },
    ],
  },
  sections: [
    {
      id: 'classes',
      title: 'My Classes',
      subtitle: 'Roster, assignments, and submissions',
      illustration: '/illustrations/sections/learn.svg',
      illustrationAlt: 'Group of students with a teacher',
      gradient: 'manage',
      studios: [],
      href: '/teacher',
    },
    {
      id: 'plan',
      title: 'Plan & Generate',
      subtitle: 'Lesson plans, question papers, NCERT browse',
      illustration: '/illustrations/sections/create.svg',
      illustrationAlt: 'Teacher with a glowing notebook',
      gradient: 'create',
      studios: [
        {
          name: 'Lesson Plans',
          href: '/teacher/lessons',
          illustration: '/illustrations/studios/story.svg',
          illustrationAlt: 'Open lesson plan with NCERT chapter',
          bg: 'bg-gradient-to-br from-violet-100 to-purple-200',
          variant: 'small',
          caption: 'NCERT-anchored',
        },
        {
          name: 'Question Papers',
          href: '/teacher/papers',
          illustration: '/illustrations/studios/quiz.svg',
          illustrationAlt: 'Question paper with multiple-choice items',
          bg: 'bg-gradient-to-br from-emerald-100 to-green-200',
          variant: 'small',
          caption: '3-variant CBSE PDFs',
        },
        {
          name: 'Curriculum',
          href: '/teacher/curriculum',
          illustration: '/illustrations/studios/books.svg',
          illustrationAlt: 'NCERT chapter index',
          bg: 'bg-gradient-to-br from-indigo-100 to-blue-200',
          variant: 'small',
          caption: 'Browse NCERT chapters',
        },
      ],
    },
    {
      id: 'review',
      title: 'Review & Feedback',
      subtitle: 'Submissions, HPC narratives, parent comms',
      illustration: '/illustrations/sections/play.svg',
      illustrationAlt: 'Teacher reviewing student work',
      gradient: 'review',
      studios: [],
      href: '/teacher',
    },
  ],
  rightRailWidgets: [],
};
