import type { CreationType } from '@/types/creation.types';
import type { Template } from './types';

/** Daily Spark prompts — 30+ per type for a full month without repeats */
const STORY_SPARKS: Template[] = [
  { id: 'spark-story-1', emoji: '🌈', title: 'Rainbow Bridge', description: 'A bridge made of rainbows connects two villages', promptText: 'A kid discovers that the rainbow after monsoon rain is actually a bridge connecting their village to a magical world on the other side', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-2', emoji: '🦜', title: 'The Talking Parrot', description: 'A parrot that tells the future', promptText: 'A family\'s pet parrot suddenly starts predicting the future, and the whole neighborhood comes to ask it questions', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-3', emoji: '🎪', title: 'Circus School', description: 'A school that teaches circus arts', promptText: 'A kid gets accepted into a secret school that teaches circus arts like trapeze, juggling, and magic tricks alongside regular subjects', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-4', emoji: '🏔️', title: 'Himalayan Mystery', description: 'A strange signal from the mountains', promptText: 'A young ham radio enthusiast in Shimla picks up a mysterious signal from high in the Himalayas and sets out to find its source', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-5', emoji: '🎨', title: 'Living Paintings', description: 'Paintings in a gallery come to life at night', promptText: 'A kid who stays late at an art gallery discovers that all the paintings come alive at night and the characters have their own society', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-6', emoji: '🐒', title: 'Monkey King of Jaipur', description: 'A monkey leads a rescue mission', promptText: 'The smartest monkey in Jaipur organizes all the city\'s monkeys to help find a lost kitten, creating hilarious chaos', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-7', emoji: '🌊', title: 'Underwater Temple', description: 'Discover a temple beneath the sea', promptText: 'While swimming off the coast of Dwarka, a kid discovers an ancient underwater temple with glowing walls and friendly sea creatures guarding it', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-8', emoji: '🎵', title: 'The Musical Tree', description: 'A tree that plays music when the wind blows', promptText: 'A tree in a kid\'s backyard starts playing beautiful music when the wind blows, and each season it plays a different raga', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-9', emoji: '🦋', title: 'Butterfly Messages', description: 'Butterflies carry secret messages', promptText: 'A kid discovers that the butterflies in their garden are actually carrying tiny messages between flowers, and reads them to uncover a beautiful secret', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-10', emoji: '🍳', title: 'The Cooking Contest', description: 'A magical cooking competition', promptText: 'A kid enters a cooking contest where the ingredients are alive and helpful: the tomatoes give advice and the spices tell jokes', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-11', emoji: '📮', title: 'Letters From the Past', description: 'A mailbox delivers letters from history', promptText: 'An old mailbox in a kid\'s house starts delivering letters from kids who lived in the same house a hundred years ago', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-12', emoji: '🌺', title: 'The Garden Guardian', description: 'A tiny guardian protects your garden', promptText: 'A kid finds a tiny warrior (no bigger than their thumb) living in their garden, protecting the plants from invisible pests', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-13', emoji: '🚂', title: 'Magic Train Ride', description: 'A train to impossible destinations', promptText: 'A kid boards a regular-looking train at a small Indian station, but each stop is a completely different magical world', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-14', emoji: '🎭', title: 'Shadow Puppet Show', description: 'Shadows come alive and tell stories', promptText: 'During a power cut, a kid discovers that their shadow can move on its own and wants to put on a puppet show using other shadows', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-15', emoji: '🏡', title: 'The Tiny Door', description: 'A tiny door appears in the wall', promptText: 'A kid notices a tiny door (10 cm tall) that appeared overnight in their bedroom wall, and when they look through it, they see a miniature world', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-16', emoji: '🌟', title: 'Star Collector', description: 'Collecting fallen stars in a jar', promptText: 'A kid discovers that fallen stars land in their backyard as tiny glowing orbs, and collects them in jars to light up their village during blackouts', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-17', emoji: '🐕', title: 'Dog Detective', description: 'A stray dog solves neighborhood mysteries', promptText: 'A stray dog in the neighborhood is actually super intelligent and helps kids solve mysteries like missing lunch boxes and stolen cricket balls', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-18', emoji: '🎓', title: 'The Backwards Day', description: 'Everything happens in reverse at school', promptText: 'One morning, a kid wakes up and everything at school is backwards: class starts with recess and ends with assembly, and everyone walks backwards', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-19', emoji: '🌻', title: 'The Sunflower Code', description: 'Sunflowers hide a secret message', promptText: 'A field of sunflowers near a kid\'s house always faces the same direction, not the sun, and they discover the flowers are pointing to a hidden treasure', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-20', emoji: '🎮', title: 'Inside the Game', description: 'Getting sucked into a video game', promptText: 'A kid gets pulled into their favorite video game and must complete all the levels using real-world skills to get back home', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-21', emoji: '🐢', title: 'The Wise Turtle', description: 'A 200-year-old turtle shares wisdom', promptText: 'A kid finds a turtle in their grandmother\'s pond that is 200 years old and can share memories of everything it has seen', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-22', emoji: '🏖️', title: 'Sand Castle Kingdom', description: 'A sand castle becomes a real kingdom', promptText: 'A kid builds an elaborate sand castle at Goa beach, and overnight it grows into a real tiny kingdom with sand people who need a ruler', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-23', emoji: '📱', title: 'The App That Listens', description: 'An app that understands animal languages', promptText: 'A kid accidentally codes an app that translates animal sounds into human language, and discovers what the neighborhood animals really think about humans', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-24', emoji: '🎪', title: 'Cloud Shapes', description: 'Cloud shapes become real', promptText: 'A kid discovers that whatever shape they see in the clouds actually comes to life and lands in their backyard for a day', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-25', emoji: '🏀', title: 'Sports Day Swap', description: 'Animals and kids swap sports day', promptText: 'On Sports Day, all the school children swap abilities with animals: the shy kid runs like a cheetah, while another swims like a dolphin', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-26', emoji: '🌍', title: 'Pen Pal Planet', description: 'Getting a pen pal from another planet', promptText: 'A kid gets a pen pal assignment at school, but their pen pal turns out to be a kid from another planet who is also doing a school project', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-27', emoji: '🎂', title: 'Birthday Wishes', description: 'Birthday wishes that actually come true', promptText: 'On their birthday, a kid blows out the candles and their wish comes true, but it keeps coming true for every wish they make all day, with unexpected results', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-28', emoji: '🔮', title: 'The Dream Catcher', description: 'A dream catcher that shows other people\'s dreams', promptText: 'A kid gets a dream catcher from a local fair that lets them see other people\'s dreams, and they discover that their grumpy neighbor has the most wonderful dreams', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-29', emoji: '🎪', title: 'The Invisible Friend', description: 'An imaginary friend becomes real', promptText: 'A kid\'s imaginary friend suddenly becomes visible to everyone, and the friend is from a world where everything is the opposite of ours', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-30', emoji: '🌮', title: 'The Recipe Book', description: 'A cookbook with magical recipes', promptText: 'A kid finds their grandmother\'s old recipe book, but these aren\'t normal recipes. Each dish gives you a temporary superpower', category: 'Daily Spark', type: 'story' },
  { id: 'spark-story-31', emoji: '🎈', title: 'Balloon Adventure', description: 'A balloon that takes you anywhere', promptText: 'A kid buys a balloon at a mela that doesn\'t just float. It can fly them anywhere they want to go, but only for one hour at a time', category: 'Daily Spark', type: 'story' },
];

const MUSIC_SPARKS: Template[] = [
  { id: 'spark-music-1', emoji: '🌅', title: 'Dawn Chorus', description: 'Music inspired by birdsong at sunrise', promptText: 'A peaceful track inspired by the sound of birds singing at dawn in a quiet Indian village', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'classical' } },
  { id: 'spark-music-2', emoji: '🎪', title: 'Mela Madness', description: 'The excitement of a village fair', promptText: 'An exciting, bustling song capturing the energy and joy of a village mela with rides, food, and games', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'folk' } },
  { id: 'spark-music-3', emoji: '🌊', title: 'Ocean Waves', description: 'Calming sounds of the sea', promptText: 'A tranquil track blending ocean waves with gentle flute melodies, like sitting on a Goa beach at sunset', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'electronic' } },
  { id: 'spark-music-4', emoji: '🎮', title: 'Game On', description: 'An epic video game soundtrack', promptText: 'An exciting 8-bit inspired video game soundtrack for the final boss level, with electronic beats and dramatic buildups', category: 'Daily Spark', type: 'music', settings: { mood: 'epic', genre: 'electronic' } },
  { id: 'spark-music-5', emoji: '🏃', title: 'Run to Win', description: 'Pump-up music for sports day', promptText: 'A motivational pump-up track for sports day that makes you feel like you can run faster and jump higher', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'pop' } },
  { id: 'spark-music-6', emoji: '🌙', title: 'Moonlight Serenade', description: 'A gentle nighttime melody', promptText: 'A gentle, dreamy melody for a quiet moonlit night on a rooftop, with soft strings and piano', category: 'Daily Spark', type: 'music', settings: { mood: 'dreamy', genre: 'classical' } },
  { id: 'spark-music-7', emoji: '🎓', title: 'Study Beats', description: 'Lo-fi beats for homework time', promptText: 'Chill lo-fi study beats with a light Indian classical touch, perfect for focusing on homework', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'electronic' } },
  { id: 'spark-music-8', emoji: '🎭', title: 'Drama Queen', description: 'Over-the-top theatrical music', promptText: 'A dramatic, theatrical piece like a Bollywood movie climax scene with building tension and a triumphant finish', category: 'Daily Spark', type: 'music', settings: { mood: 'epic', genre: 'pop' } },
  { id: 'spark-music-9', emoji: '🌻', title: 'Garden Party', description: 'Happy music for a garden gathering', promptText: 'A light, happy acoustic song for a garden birthday party with friends, full of warmth and celebration', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'folk' } },
  { id: 'spark-music-10', emoji: '🚂', title: 'Train Journey', description: 'The rhythm of a train on tracks', promptText: 'A rhythmic song inspired by the clickety-clack of an Indian train journey, watching the scenery pass by from the window', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'folk' } },
  { id: 'spark-music-11', emoji: '👑', title: 'Royal March', description: 'March like a king or queen', promptText: 'A majestic, regal march like a king or queen entering their palace, with brass instruments and drums', category: 'Daily Spark', type: 'music', settings: { mood: 'epic', genre: 'classical' } },
  { id: 'spark-music-12', emoji: '🎵', title: 'Friendship Anthem', description: 'A song for best friends', promptText: 'A heartfelt pop anthem about friendship, laughing together, and always having each other\'s backs', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'pop' } },
  { id: 'spark-music-13', emoji: '🌧️', title: 'Monsoon Dance', description: 'Dancing in the first rain', promptText: 'A joyful, splashy song about dancing in the first rain of monsoon season with paper boats and puddle jumping', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'pop' } },
  { id: 'spark-music-14', emoji: '🎸', title: 'Street Jam', description: 'Street musicians coming together', promptText: 'A funky jam session of street musicians from different parts of India coming together, each adding their unique sound', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'rock' } },
  { id: 'spark-music-15', emoji: '🌃', title: 'City Lights', description: 'The sound of a bustling city at night', promptText: 'A modern electronic track capturing the energy of Mumbai or Delhi at night: traffic, neon lights, and people everywhere', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'electronic' } },
  { id: 'spark-music-16', emoji: '🎹', title: 'Piano Stories', description: 'A piano tells a story without words', promptText: 'A beautiful solo piano piece that tells a story without any words, starting soft, building to a climax, and ending gently', category: 'Daily Spark', type: 'music', settings: { mood: 'dreamy', genre: 'classical' } },
  { id: 'spark-music-17', emoji: '🏀', title: 'Victory Lap', description: 'Winning the championship', promptText: 'A triumphant celebration song for when you score the winning goal or hit the winning run. Pure joy and excitement', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'pop' } },
  { id: 'spark-music-18', emoji: '🦚', title: 'Peacock Dance', description: 'The grace of a dancing peacock', promptText: 'An elegant, colorful piece inspired by a peacock dancing in the rain, graceful, beautiful, and uniquely Indian', category: 'Daily Spark', type: 'music', settings: { mood: 'dreamy', genre: 'classical' } },
  { id: 'spark-music-19', emoji: '🎶', title: 'Homework Rap', description: 'Rapping about school life', promptText: 'A funny rap about the struggles of homework, waking up early, and surviving school, with a positive twist at the end', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'hip-hop' } },
  { id: 'spark-music-20', emoji: '🌸', title: 'Spring Melody', description: 'The arrival of spring in India', promptText: 'A bright, cheerful melody celebrating the arrival of spring with blooming flowers, kite flying, and warm sunshine', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'folk' } },
  { id: 'spark-music-21', emoji: '🎺', title: 'Brass Band', description: 'A lively Indian wedding band', promptText: 'A fun, lively brass band song like the ones at Indian weddings, with trumpets, drums, and dancing in the streets', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'folk' } },
  { id: 'spark-music-22', emoji: '🧘', title: 'Yoga Flow', description: 'Calm music for stretching and breathing', promptText: 'A calm, flowing piece for yoga or meditation with gentle nature sounds, singing bowls, and soft flute', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'classical' } },
  { id: 'spark-music-23', emoji: '🚗', title: 'Road Trip', description: 'Music for a family road trip', promptText: 'An upbeat road trip song for a family drive through the Indian countryside, singing along with the windows down', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'rock' } },
  { id: 'spark-music-24', emoji: '🌌', title: 'Space Walk', description: 'Floating through outer space', promptText: 'An atmospheric, ethereal track of floating through outer space, seeing galaxies and nebulas all around', category: 'Daily Spark', type: 'music', settings: { mood: 'dreamy', genre: 'electronic' } },
  { id: 'spark-music-25', emoji: '🎊', title: 'New Year Celebration', description: 'Ring in the new year', promptText: 'A countdown and celebration song for New Year\'s Eve with building excitement, confetti, and fireworks sounds', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'pop' } },
  { id: 'spark-music-26', emoji: '📖', title: 'Storyteller', description: 'A musical narration', promptText: 'A musical piece that tells a story through melodies, like a narrator who speaks only through music, from once upon a time to happily ever after', category: 'Daily Spark', type: 'music', settings: { mood: 'dreamy', genre: 'folk' } },
  { id: 'spark-music-27', emoji: '🎤', title: 'Karaoke Night', description: 'Singing with friends', promptText: 'A fun, catchy karaoke song about having fun with friends, perfect for singing at the top of your lungs', category: 'Daily Spark', type: 'music', settings: { mood: 'happy', genre: 'pop' } },
  { id: 'spark-music-28', emoji: '🎻', title: 'Violin Dream', description: 'A soulful violin piece', promptText: 'A soulful violin melody that starts slow and gentle, then builds into something powerful and emotional', category: 'Daily Spark', type: 'music', settings: { mood: 'epic', genre: 'classical' } },
  { id: 'spark-music-29', emoji: '🐦', title: 'Bird Song', description: 'A duet with nature', promptText: 'A musical conversation between a flute player and the birds in a forest, where the birds respond to each melody', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'folk' } },
  { id: 'spark-music-30', emoji: '🎪', title: 'Circus Theme', description: 'A fun circus performance', promptText: 'A playful, exciting circus theme with acrobatic energy, clown humor, and a grand finale moment', category: 'Daily Spark', type: 'music', settings: { mood: 'energetic', genre: 'pop' } },
  { id: 'spark-music-31', emoji: '🌿', title: 'Forest Walk', description: 'Walking through a peaceful forest', promptText: 'A gentle nature walk soundtrack with crunching leaves, flowing streams, and soft wind through the trees', category: 'Daily Spark', type: 'music', settings: { mood: 'chill', genre: 'electronic' } },
];

const QUIZ_SPARKS: Template[] = [
  { id: 'spark-quiz-1', emoji: '🧪', title: 'Weird Science', description: 'Strange but true science facts', promptText: 'Strange but true science facts: weird animal abilities, unusual chemical reactions, and mind-blowing physics', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-2', emoji: '🗿', title: 'World Wonders', description: 'Amazing structures and monuments', promptText: 'Amazing world wonders: ancient and modern, including Indian heritage sites like Taj Mahal, Hampi, and Ajanta caves', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-3', emoji: '🎬', title: 'Bollywood Trivia', description: 'Fun facts about Hindi cinema', promptText: 'Fun Bollywood trivia: famous movies, actors, songs, and behind-the-scenes facts about Indian cinema', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-4', emoji: '🌋', title: 'Natural Disasters', description: 'Earthquakes, volcanoes, and storms', promptText: 'Natural phenomena: earthquakes, volcanoes, tsunamis, and how scientists predict and prepare for them', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-5', emoji: '🔢', title: 'Math Magic', description: 'Fun math puzzles and number facts', promptText: 'Math magic: number patterns, famous mathematicians like Ramanujan, and fun math puzzles and tricks', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-6', emoji: '🌏', title: 'Planet Earth', description: 'How our planet works', promptText: 'Planet Earth: continents, oceans, climate zones, and amazing facts about our planet', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-7', emoji: '🦕', title: 'Dinosaur World', description: 'Everything about dinosaurs', promptText: 'Dinosaurs: types, sizes, what they ate, how they lived, and why they went extinct', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-8', emoji: '💡', title: 'Inventions & Inventors', description: 'Who invented what?', promptText: 'Famous inventions and inventors: from ancient India to modern technology, including Indian scientists and their discoveries', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-9', emoji: '🎨', title: 'Art & Artists', description: 'Famous paintings and artists', promptText: 'Art around the world: famous paintings, artists like Raja Ravi Varma and MF Husain, art styles, and fun art history', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-10', emoji: '🌿', title: 'Trees & Plants', description: 'The amazing world of plants', promptText: 'The amazing world of plants: how trees grow, medicinal plants used in Ayurveda, and fascinating plant facts', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-11', emoji: '🎯', title: 'Indian Languages', description: 'Diversity of Indian languages', promptText: 'Indian languages: how many languages India has, scripts, common phrases, and the amazing diversity of Indian linguistics', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-12', emoji: '🧬', title: 'DNA & Genetics', description: 'How genetics work', promptText: 'DNA and genetics: how traits are inherited, what genes do, and amazing facts about the human genome', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-13', emoji: '🏛️', title: 'Indian Constitution', description: 'Know your rights and democracy', promptText: 'The Indian Constitution: fundamental rights, how democracy works, who were the framers, and important amendments', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-14', emoji: '🌐', title: 'Internet & Tech', description: 'How the internet works', promptText: 'Internet and technology: how the web works, coding basics, cybersafety, and the history of computers', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-15', emoji: '🐝', title: 'Insects & Bugs', description: 'The tiny creatures around us', promptText: 'Insects and bugs: ants, bees, butterflies, beetles, and their incredible abilities and importance to nature', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-16', emoji: '🏰', title: 'Indian Forts', description: 'Mighty forts of India', promptText: 'Famous Indian forts: Red Fort, Golconda, Mehrangarh, Chittorgarh, and the stories behind these mighty structures', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-17', emoji: '⚽', title: 'Sports Around the World', description: 'Different sports from every continent', promptText: 'Sports from around the world: kabaddi, sumo, lacrosse, cricket, and unique sports from different countries', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-18', emoji: '🌡️', title: 'Weather & Climate', description: 'How weather works', promptText: 'Weather and climate: how monsoons form, what causes rainbows, thunderstorms, and climate change basics', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-19', emoji: '🎵', title: 'Music Trivia', description: 'Musical instruments and famous musicians', promptText: 'Music trivia: Indian classical music, ragas, famous musicians like AR Rahman and Lata Mangeshkar, and world music', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-20', emoji: '🧭', title: 'Explorers & Adventures', description: 'Famous explorations and discoveries', promptText: 'Famous explorers and discoveries: from Vasco da Gama reaching India to space exploration, expeditions that changed the world', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-21', emoji: '🐠', title: 'Ocean Life', description: 'Creatures of the deep sea', promptText: 'Ocean life: coral reefs, deep sea creatures, marine biodiversity, and how the ocean affects our planet', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-22', emoji: '📚', title: 'Famous Books', description: 'Classic stories and their authors', promptText: 'Famous books and authors: Panchatantra, Harry Potter, Ruskin Bond, and classic stories every kid should know', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-23', emoji: '🏗️', title: 'How Things Work', description: 'Everyday machines explained', promptText: 'How everyday things work: elevators, refrigerators, Wi-Fi, airplanes, and the science behind technology we use daily', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-24', emoji: '🐘', title: 'Endangered Species', description: 'Animals that need our help', promptText: 'Endangered species: animals at risk in India and worldwide, conservation efforts, and what kids can do to help', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-25', emoji: '🎭', title: 'Indian Dance Forms', description: 'Classical and folk dances of India', promptText: 'Indian dance forms: Bharatanatyam, Kathak, Bhangra, Garba, and the rich tradition of dance across Indian states', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-26', emoji: '🚀', title: 'Future Tech', description: 'Technology of tomorrow', promptText: 'Future technology: AI, robots, self-driving cars, space tourism, and what life might look like in 2050', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-27', emoji: '🎨', title: 'Colors & Light', description: 'The science of colors', promptText: 'Colors and light: how we see color, why the sky is blue, how rainbows form, and optical illusions', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-28', emoji: '🍎', title: 'Nutrition & Health', description: 'Eating right and staying healthy', promptText: 'Nutrition and health: vitamins, superfoods, Indian spices and their health benefits, and how to stay healthy', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-29', emoji: '🗣️', title: 'Communication', description: 'How we share ideas', promptText: 'Communication through history: from cave paintings to emojis, Morse code, sign language, and how the internet changed how we talk', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-30', emoji: '🧩', title: 'Logic Puzzles', description: 'Brain teasers and riddles', promptText: 'Logic puzzles, brain teasers, and riddles: pattern recognition, sequence puzzles, and lateral thinking challenges', category: 'Daily Spark', type: 'quiz' },
  { id: 'spark-quiz-31', emoji: '🎪', title: 'Record Breakers', description: 'Amazing world records', promptText: 'Guinness World Records: the tallest, fastest, biggest, and weirdest records, including records held by Indians', category: 'Daily Spark', type: 'quiz' },
];

const COMIC_SPARKS: Template[] = [
  { id: 'spark-comic-1', emoji: '🦸', title: 'Super Substitute', description: 'A substitute teacher with superpowers', promptText: 'A substitute teacher shows up with actual superpowers but tries to act normal, levitating chalk, freezing spitballs mid-air, and reading minds during tests', category: 'Daily Spark', type: 'comic', settings: { style: 'superhero' } },
  { id: 'spark-comic-2', emoji: '🐕', title: 'Dog Park Chaos', description: 'Dogs take over the city park', promptText: 'All the neighborhood dogs secretly organize a rebellion, take over the city park, and set up their own government with a pug as president', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-3', emoji: '🎮', title: 'Game Glitch', description: 'A video game character escapes into the real world', promptText: 'A character from a kid\'s favorite video game glitches out of the screen and into their bedroom, causing pixelated chaos everywhere they go', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-4', emoji: '🍕', title: 'Pizza Planet', description: 'A pizza delivery to outer space', promptText: 'A pizza delivery kid accidentally delivers to an alien spaceship and gets pulled into a galactic pizza-making competition', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-5', emoji: '🏏', title: 'Cricket Clash', description: 'Humans vs robots in a cricket match', promptText: 'A team of kids challenges a team of cricket-playing robots to a match, using clever tricks to outsmart the machines', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-6', emoji: '🎒', title: 'Backpack Portal', description: 'A school bag that opens to another world', promptText: 'A kid opens their school backpack and falls into a fantasy world where homework is currency and erasers are magical artifacts', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-7', emoji: '🧪', title: 'Lab Accident', description: 'A science experiment creates a tiny monster', promptText: 'A kid\'s science experiment accidentally creates a tiny, adorable monster that eats only homework and grows bigger with each page it consumes', category: 'Daily Spark', type: 'comic', settings: { style: 'chibi' } },
  { id: 'spark-comic-8', emoji: '🌙', title: 'Midnight Snack Heist', description: 'Sneaking to the kitchen at midnight', promptText: 'A kid sneaks to the kitchen for a midnight snack and discovers all the food items are alive and having their own party', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-9', emoji: '🦊', title: 'Fox Detective', description: 'A clever fox solves a forest mystery', promptText: 'A detective fox in a tiny hat investigates who stole all the mangoes from the forest\'s mango tree, interrogating suspicious monkeys', category: 'Daily Spark', type: 'comic', settings: { style: 'indie' } },
  { id: 'spark-comic-10', emoji: '⚡', title: 'Storm Chasers', description: 'Kids who ride lightning bolts', promptText: 'A group of brave kids discover they can ride lightning bolts during monsoon storms and use this power to deliver mail across India in seconds', category: 'Daily Spark', type: 'comic', settings: { style: 'superhero' } },
  { id: 'spark-comic-11', emoji: '🎪', title: 'Circus Escape', description: 'Animals escape the circus for an adventure', promptText: 'The animals at a traveling circus decide to escape and see the city, but a baby elephant, a juggling monkey, and a shy tiger have no idea how traffic works', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-12', emoji: '📱', title: 'App Gone Wrong', description: 'A phone app that controls reality', promptText: 'A kid downloads a mysterious app that controls the weather, gravity, and time, but every button press causes hilarious unintended side effects', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-13', emoji: '🏫', title: 'School at Night', description: 'What happens at school after midnight', promptText: 'A kid forgets their bag at school and sneaks back at night to discover the classroom furniture comes alive and the blackboard tells scary stories', category: 'Daily Spark', type: 'comic', settings: { style: 'indie' } },
  { id: 'spark-comic-14', emoji: '🛸', title: 'Alien Tourist', description: 'Showing an alien around India', promptText: 'An alien crash-lands in a kid\'s backyard and the kid must show them around India before their parents come to pick them up in a flying saucer', category: 'Daily Spark', type: 'comic', settings: { style: 'chibi' } },
  { id: 'spark-comic-15', emoji: '🎂', title: 'Cake Wars', description: 'A baking competition goes wild', promptText: 'A school baking competition goes wrong when everyone\'s cakes come alive and start a food fight in the cafeteria', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-16', emoji: '🐒', title: 'Monkey Business', description: 'Monkeys steal a kid\'s homework', promptText: 'A troop of monkeys in Jaipur steals a kid\'s homework and the kid must negotiate with the monkey king to get it back before school', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-17', emoji: '🚀', title: 'Space Dabbawala', description: 'Delivering lunch boxes in space', promptText: 'A Mumbai dabbawala accidentally boards a rocket and must now deliver lunch boxes to astronauts on the International Space Station', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-18', emoji: '🎭', title: 'Shadow Swap', description: 'A kid\'s shadow has a mind of its own', promptText: 'A kid discovers their shadow has its own personality and starts doing embarrassing things independently, dancing during assembly, making faces at teachers', category: 'Daily Spark', type: 'comic', settings: { style: 'indie' } },
  { id: 'spark-comic-19', emoji: '🦋', title: 'Shrink Ray', description: 'Accidentally shrunk to the size of an ant', promptText: 'A kid finds a shrink ray in their attic and accidentally zaps themselves, now they must navigate their own garden like a jungle while their dog thinks they are a toy', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-20', emoji: '🏆', title: 'Sports Swap Day', description: 'Everyone must play the wrong sport', promptText: 'On Sports Day, the principal mixes up all the teams: the chess club plays kabaddi, the cricket team does ballet, and the swimmers play badminton', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-21', emoji: '🌋', title: 'Volcano Island', description: 'Stranded on an island with a friendly volcano', promptText: 'A class picnic boat drifts to a tiny island where the volcano is actually friendly and tells jokes, but it sneezes lava when it laughs too hard', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-22', emoji: '📚', title: 'Library Portal', description: 'Books in the library open real portals', promptText: 'A kid discovers that certain books in the school library are actually portals. Opening a dinosaur book teleports you to the Jurassic era', category: 'Daily Spark', type: 'comic', settings: { style: 'superhero' } },
  { id: 'spark-comic-23', emoji: '🎤', title: 'Karaoke Curse', description: 'Singing makes magical things happen', promptText: 'A kid sings at a karaoke night and discovers their singing voice has magical powers: sad songs make it rain, happy songs make flowers bloom instantly', category: 'Daily Spark', type: 'comic', settings: { style: 'chibi' } },
  { id: 'spark-comic-24', emoji: '🦁', title: 'Zoo Breakout', description: 'Animals from the zoo visit the neighborhood', promptText: 'The zoo animals politely walk out for a day off and visit the neighborhood: a lion tries to order chai, a penguin goes to the mall, and a giraffe peeks into apartments', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-25', emoji: '🧲', title: 'Magnet Kid', description: 'A kid who becomes magnetic', promptText: 'After a science experiment, a kid becomes magnetic: spoons, keys, and everyone\'s phones stick to them. They must get through a school day without attracting everything metal', category: 'Daily Spark', type: 'comic', settings: { style: 'superhero' } },
  { id: 'spark-comic-26', emoji: '🌈', title: 'Color Thief', description: 'Someone is stealing colors from the world', promptText: 'Colors start disappearing from the world. First the sky turns gray, then flowers lose their petals\' hues. A kid must find the Color Thief and bring the colors back', category: 'Daily Spark', type: 'comic', settings: { style: 'indie' } },
  { id: 'spark-comic-27', emoji: '🧁', title: 'Magic Bakery', description: 'A bakery where treats give you powers', promptText: 'A neighborhood bakery sells cupcakes that give temporary superpowers: the chocolate one gives super strength, vanilla gives flight, but strawberry makes you speak in rhymes', category: 'Daily Spark', type: 'comic', settings: { style: 'chibi' } },
  { id: 'spark-comic-28', emoji: '🚲', title: 'The Race', description: 'An epic bicycle race through the city', promptText: 'An epic bicycle race through the streets of Bangalore where kids must dodge auto-rickshaws, jump over speed bumps, and outsmart the neighborhood bully to win the trophy', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
  { id: 'spark-comic-29', emoji: '👻', title: 'Friendly Ghost', description: 'A ghost that is terrible at scaring people', promptText: 'A ghost haunting an old house is terrible at scaring people. Every time it tries to be scary, it accidentally does something helpful instead, like organizing the bookshelf', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-30', emoji: '🎯', title: 'Homework Machine', description: 'An invention that does homework for you', promptText: 'A kid builds a machine that does homework automatically, but it starts getting creative, writing poetry for math answers and drawing comics for science diagrams', category: 'Daily Spark', type: 'comic', settings: { style: 'cartoon' } },
  { id: 'spark-comic-31', emoji: '🌊', title: 'Surf\'s Up', description: 'Surfing with dolphins and sea creatures', promptText: 'A kid discovers they can surf impossibly well and catches a wave that takes them far out to sea, where dolphins challenge them to an underwater surfing competition', category: 'Daily Spark', type: 'comic', settings: { style: 'manga' } },
];

const SPARK_POOLS: Record<string, Template[]> = {
  story: STORY_SPARKS,
  music: MUSIC_SPARKS,
  quiz: QUIZ_SPARKS,
  comic: COMIC_SPARKS,
};

/**
 * Simple hash of a date string to get a deterministic index.
 * Same date = same spark for all users.
 */
function dateHash(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

/**
 * Returns the Daily Spark for a given creation type.
 * Deterministic based on date — same spark all day for all users.
 */
export function getDailySpark(type: CreationType): Template | null {
  const pool = SPARK_POOLS[type];
  if (!pool || pool.length === 0) return null;

  const today = new Date().toISOString().split('T')[0] ?? '';
  const index = dateHash(today) % pool.length;
  return pool[index] ?? null;
}
