import type { Template } from './types';

export const STORY_TEMPLATES: Template[] = [
  // Adventure
  {
    id: 'story-jungle-quest',
    emoji: '🌴',
    title: 'Jungle Quest',
    description: 'Explore a mysterious Indian jungle with talking animals',
    promptText: 'A kid discovers a hidden path in the Western Ghats jungle that leads to a secret village of talking animals who need help saving their home',
    category: 'Adventure',
    type: 'story',
    settings: { genre: 'adventure' },
  },
  {
    id: 'story-time-travel',
    emoji: '⏰',
    title: 'Time Travel School Trip',
    description: 'Travel back in time during a school field trip',
    promptText: 'During a school trip to a museum in Delhi, a student accidentally activates an ancient device that sends them back to the Mughal era',
    category: 'Adventure',
    type: 'story',
    settings: { genre: 'adventure' },
  },
  // Fantasy
  {
    id: 'story-magic-library',
    emoji: '📚',
    title: 'The Magic Library',
    description: 'Books come alive in a secret library',
    promptText: 'A kid finds a hidden library under their school where every book is alive and the characters jump out to ask for help finishing their stories',
    category: 'Fantasy',
    type: 'story',
    settings: { genre: 'fantasy' },
  },
  {
    id: 'story-flying-carpet',
    emoji: '🪄',
    title: 'The Flying Carpet',
    description: 'A magical carpet takes you across India',
    promptText: 'A kid inherits a dusty old carpet from their grandparent that turns out to be a flying carpet, and it takes them on a tour of the most magical places in India',
    category: 'Fantasy',
    type: 'story',
    settings: { genre: 'fantasy' },
  },
  // Sci-Fi
  {
    id: 'story-robot-friend',
    emoji: '🤖',
    title: 'My Robot Best Friend',
    description: 'Build a robot that becomes your best friend',
    promptText: 'A kid builds a robot from old computer parts for a school science fair, but the robot develops a personality and becomes their best friend',
    category: 'Sci-Fi',
    type: 'story',
    settings: { genre: 'sci-fi' },
  },
  {
    id: 'story-space-cricket',
    emoji: '🏏',
    title: 'Space Cricket Match',
    description: 'Play cricket against aliens in outer space',
    promptText: 'India\'s junior cricket team is invited to play an intergalactic cricket tournament on a space station against friendly alien teams',
    category: 'Sci-Fi',
    type: 'story',
    settings: { genre: 'sci-fi' },
  },
  // Indian Mythology
  {
    id: 'story-ganesha-coding',
    emoji: '🐘',
    title: 'Ganesha Learns Coding',
    description: 'Lord Ganesha tries to learn coding',
    promptText: 'In a funny modern retelling, young Ganesha decides to learn coding and builds an app, but hilarious things happen when his mouse (vehicle) keeps clicking the wrong buttons',
    category: 'Indian Mythology',
    type: 'story',
    settings: { genre: 'funny' },
  },
  {
    id: 'story-hanuman-superhero',
    emoji: '🦸',
    title: 'Hanuman: Modern Superhero',
    description: 'Hanuman saves the day in a modern city',
    promptText: 'A modern retelling where a young kid with Hanuman-like powers saves their city from a flood using courage, teamwork, and clever thinking',
    category: 'Indian Mythology',
    type: 'story',
    settings: { genre: 'adventure' },
  },
  // Friendship
  {
    id: 'story-new-kid',
    emoji: '🤝',
    title: 'The New Kid',
    description: 'Making friends with someone different',
    promptText: 'A new student joins a school in Chennai from a completely different state, and they don\'t speak the same language but become best friends through their shared love of art',
    category: 'Friendship',
    type: 'story',
    settings: { genre: 'friendship' },
  },
  // School Life
  {
    id: 'story-science-fair',
    emoji: '🔬',
    title: 'Science Fair Surprise',
    description: 'A science experiment goes hilariously wrong',
    promptText: 'A student\'s science fair volcano project accidentally creates real mini-volcanoes all over the school, and they must use science to fix it before the principal finds out',
    category: 'School Life',
    type: 'story',
    settings: { genre: 'funny' },
  },
  // Animal Kingdom
  {
    id: 'story-tiger-detective',
    emoji: '🐅',
    title: 'Tiger Detective',
    description: 'A Bengal tiger solves mysteries in the forest',
    promptText: 'A clever Bengal tiger in the Sundarbans becomes a detective and solves the mystery of why the river fish are disappearing, discovering an unexpected culprit',
    category: 'Animal Kingdom',
    type: 'story',
    settings: { genre: 'mystery' },
  },
  // Space
  {
    id: 'story-isro-kid',
    emoji: '🚀',
    title: 'ISRO Junior Astronaut',
    description: 'Become the youngest ISRO astronaut',
    promptText: 'A 12-year-old wins a contest to become ISRO\'s youngest junior astronaut and joins the Gaganyaan mission, discovering something incredible on the journey',
    category: 'Space',
    type: 'story',
    settings: { genre: 'sci-fi' },
  },
  {
    id: 'story-moon-village',
    emoji: '🌙',
    title: 'Moon Village',
    description: 'Discover a hidden village on the moon',
    promptText: 'A kid looking through a telescope spots something moving on the moon and convinces a scientist to investigate, revealing a tiny civilization living in moon craters',
    category: 'Space',
    type: 'story',
    settings: { genre: 'fantasy' },
  },
];

export const STORY_CATEGORIES = [...new Set(STORY_TEMPLATES.map((t) => t.category))];
